<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f388b2c9-172e-4710-a8ab-ce946864f698</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Pages\GpiSupplyChain.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Pages\About.cshtml~RF80d911fa.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="EPPlus" Version="8.5.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

</Project>
